.TH PHPCLIBROWSER 1
.SH NAME
phpclibrowser \- run php cli in a web window
.SH SYNOPSIS
.B phpclibrowser
[\fB\-d\fR \fworking_directory\fR]
[\fB\-s\fR \fphpscript_directory\fR]
.IR file ...
.SH DESCRIPTION
.B phpclibrowser
runs php cli scrips and displays results in a stand alone web window.
.SH OPTIONS
.TP
.BR \-s =\fIphp script location\fR
Set the path of the php script to run.
Defaults to its onw example/test scitp.
Usually points to the index.php directory.
